language: ruby
rvm:
 - "1.9"
 - "2.0"
 - 2.1.0
 - 2.1.3
 - ruby-head

before_install:
 - echo "yes" | sudo apt-add-repository ppa:zoogie/sdl2-snapshots
 - sudo apt-get update -qq
 - sudo apt-get install -qq build-essential libsdl2-dev libsdl2-ttf-dev libpango1.0-dev libgl1-mesa-dev libfreeimage-dev libopenal-dev libsndfile-dev
script:
 - bundle exec rspec

matrix:
  fast_finish: true
  allow_failures:
   - rvm: "1.9"
   - rvm: "2.0"
   - rvm: 2.1.0
   - rvm: ruby-head
